[local]
localhost ansible_connection=local ansible_user=marina

[vm]
test-vm ansible_host=YOUR_VM_IP ansible_user=root

[docker_hosts:children]
local
vm

[all:vars]
ansible_python_interpreter=/usr/bin/python3